### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by exalted** [Dresel/BuildTools.StyleCopPlus#1]
What's the difference between this and https://github.com/Dresel/StyleCopPlus.MSBuild please?

Thank you.

**Comment by Dresel** [comment]
There are two StyleCop Build Integration Nuget packages out there: https://www.nuget.org/packages/StyleCop.MSBuild/ and https://www.nuget.org/packages/BuildTools.StyleCop/ for which I added the StyleCopPlus package. They are technically more or less the same (the BuildTools.StyleCop package does add a few more parameter to the .csproj File, like StyleCopEnabled / StyleCopTreatErrorsAsWarnings). If you are not already using one of this packages, it doesn't matter which one to use (you could go for MSBuild version because it is more popular).

**Comment by exalted** [comment]
Thanks!
